### PR TITLE
WIP: Add headers for replication code.

### PR DESCRIPTION
**Pull request by thedodd**
NOTE: still making a few changes here, but there are lots of features that folks will want with this. We'll want to add a decent number of features and such so that folks can choose the code they need to include & compile.

@bluejekyll just a quick heads-up. These replication headers were all added based on a PG 11 installation. I have not checked to see if any of the headers are missing or bearing a different name.

Perhaps we could actually build up the targets dynamically in the build.rs script. That way we don't need to maintain a header with hardcoded paths which may break from version to version.

We will have to ensure that any non-pg_sys abstractions built on top of version specific types are feature gated and such ... but that will be needed regardless.

### CODE REVIEW

**Comment by bluejekyll** [comment]
See my review comment: 

> need to maintain a header with hardcoded paths which may break from version to version.

I kinda like having the explicit entries, rather than making it dynamic, as the header file will probably be easier to maintain.

That said, we could have a header per version and use our version feature selection as the means to determine which to include? Maybe even attach additional headers based on other feature flags? Just a thought.

This appears to work on pg10 though. I really need to get test coverage across all supported pg versions.

**Comment by bluejekyll** [comment]
Also in the future, if you set the pr to draft then There’s no concern of accidentally merging before it’s ready.

**Comment by thedodd** [comment]
@bluejekyll yea, sorry about that. Normally I would. I didn't originally intend to make further changes, and then I realized that there were other headers that I needed to add. Sorry about that. I'll ping you once I'm got this stuff cleaned up and ready to rock.

**Comment by bluejekyll** [comment]
It's all good, I was just mentioning offhand. It's a nice newish feature of github.

**Comment by thedodd** [comment]
Sorry for leaving this here for so long. I'll close for now, and will re-open once I have the time to finish this up.

**Comment by bluejekyll** [comment]
Cool... looking forward to it.

**Pull request closed without merging**
